### ISSUE TITLE
David Aragon's evaluation

### ISSUE THREAD

**Issue by DavidQL** [CaptainAtlas/data_engineering_web_service#2]
I like the idea for this API and think you made a great decision to use Ruby on Rails. 

I had a number of problems getting the app set up, which are not necessarily your fault. First, the mysql2 gem wouldn't install on my system. I did some research and there a number of issues that were the same as my own, so in the end I just swapped out mysql2 with postgres, which worked well.

The next issue I ran into was that the `curl`s in `tests.sh` did not work. My server was up and running and I could load it with a browser, but running `sh tests.sh` gave me a series of these errors: `curl: (7) Failed to connect to localhost port 3000: Connection refused`.

I was able to run the Ruby specs with `rake tests`. I'm not sure if you wrote these specs (in `movie_library/tests/functional`) or if they were auto-generated. All the specs passed. If you are using these specs, one suggestion I would make is to actually test the data you are changing, instead of just testing the server response. For example, an `update` test checks that the server responded successfully, but does not actually check that the item's attributes were updated.

**Comment by CaptainAtlas** [comment]
That is wierd that the shell script was refused. I haven't heard of that issue before.
