### ISSUE TITLE
Neil Nistler's Evaluation

### ISSUE THREAD

**Issue by nnistler** [CaptainAtlas/data_engineering_web_service#7]
This app is nicely put together. I am not very familiar with ruby on rails so I had some issues getting everything up and running. The README was written so that it described the overall goal of the project but I think it could benefit from a little more instruction.

**Comment by CaptainAtlas** [comment]
As far as the ruby on rails installation, I definitely had the same issues when setting up my installation. Specifically, the bundler install and some gems that were not being installed/recognized in the gem file were the main issues I can remember. Thanks for the feedback!
